#############################################################################
# Makefile for building: MemoryEditor
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Apr 3 22:59:37 2011
# Project:  MemoryEditor.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile MemoryEditor.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Memory.cpp \
		ProcessList.cpp \
		Scanner.cpp moc_mainwindow.cpp \
		moc_ProcessList.cpp \
		moc_Scanner.cpp \
		qrc_Resource.cpp
OBJECTS       = main.o \
		mainwindow.o \
		Memory.o \
		ProcessList.o \
		Scanner.o \
		moc_mainwindow.o \
		moc_ProcessList.o \
		moc_Scanner.o \
		qrc_Resource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MemoryEditor.pro
QMAKE_TARGET  = MemoryEditor
DESTDIR       = 
TARGET        = MemoryEditor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_ProcessList.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MemoryEditor.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile MemoryEditor.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile MemoryEditor.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MemoryEditor1.0.0 || $(MKDIR) .tmp/MemoryEditor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MemoryEditor1.0.0/ && $(COPY_FILE) --parents mainwindow.h Memory.h VMA.h ProcessList.h Result.h Global.h Scanner.h .tmp/MemoryEditor1.0.0/ && $(COPY_FILE) --parents Resource.qrc .tmp/MemoryEditor1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp Memory.cpp ProcessList.cpp Scanner.cpp .tmp/MemoryEditor1.0.0/ && $(COPY_FILE) --parents mainwindow.ui ProcessList.ui .tmp/MemoryEditor1.0.0/ && (cd `dirname .tmp/MemoryEditor1.0.0` && $(TAR) MemoryEditor1.0.0.tar MemoryEditor1.0.0 && $(COMPRESS) MemoryEditor1.0.0.tar) && $(MOVE) `dirname .tmp/MemoryEditor1.0.0`/MemoryEditor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MemoryEditor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_ProcessList.cpp moc_Scanner.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ProcessList.cpp moc_Scanner.cpp
moc_mainwindow.cpp: ProcessList.h \
		Memory.h \
		VMA.h \
		Global.h \
		Result.h \
		Scanner.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_ProcessList.cpp: ProcessList.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ProcessList.h -o moc_ProcessList.cpp

moc_Scanner.cpp: Global.h \
		VMA.h \
		Result.h \
		Memory.h \
		Scanner.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Scanner.h -o moc_Scanner.cpp

compiler_rcc_make_all: qrc_Resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resource.cpp
qrc_Resource.cpp: Resource.qrc \
		res/stop.png \
		res/add.png \
		res/RAM.png \
		res/Antivirus.png \
		res/gear.png \
		res/forward.png \
		res/Search.png \
		res/save.png \
		res/undo.png \
		res/delete-red.png \
		res/RecycleBin.png \
		res/Open.png \
		res/AdminTools.png \
		res/History.png \
		res/Close.png \
		res/delete-black.png \
		res/play.png \
		res/Arrow.png
	/usr/bin/rcc -name Resource Resource.qrc -o qrc_Resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_ProcessList.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_ProcessList.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_ProcessList.h: ProcessList.ui
	/usr/bin/uic-qt4 ProcessList.ui -o ui_ProcessList.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ProcessList.h \
		Memory.h \
		VMA.h \
		Global.h \
		Result.h \
		Scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ProcessList.h \
		Memory.h \
		VMA.h \
		Global.h \
		Result.h \
		Scanner.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

Memory.o: Memory.cpp Memory.h \
		VMA.h \
		Global.h \
		Result.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Memory.o Memory.cpp

ProcessList.o: ProcessList.cpp ProcessList.h \
		ui_ProcessList.h \
		mainwindow.h \
		Memory.h \
		VMA.h \
		Global.h \
		Result.h \
		Scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProcessList.o ProcessList.cpp

Scanner.o: Scanner.cpp Scanner.h \
		Global.h \
		VMA.h \
		Result.h \
		Memory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scanner.o Scanner.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ProcessList.o: moc_ProcessList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ProcessList.o moc_ProcessList.cpp

moc_Scanner.o: moc_Scanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Scanner.o moc_Scanner.cpp

qrc_Resource.o: qrc_Resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resource.o qrc_Resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

